// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVEbSH_RtyJte26KU6-6MSdA9okN3U8U',
    appId: '1:605252089782:web:a76b4bfe68aa9a12b43317',
    messagingSenderId: '605252089782',
    projectId: 'phishsense-86ed4',
    authDomain: 'phishsense-86ed4.firebaseapp.com',
    storageBucket: 'phishsense-86ed4.firebasestorage.app',
    measurementId: 'G-QFZKG798BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1s0zmY37flRMdKJSFvxQ0vfKY__MMzY',
    appId: '1:605252089782:android:6d734a63e088eec0b43317',
    messagingSenderId: '605252089782',
    projectId: 'phishsense-86ed4',
    storageBucket: 'phishsense-86ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5p-ovphSdVojqVAaTfcnoYFDFWYrWws',
    appId: '1:605252089782:ios:94d0ad9a1367c7cdb43317',
    messagingSenderId: '605252089782',
    projectId: 'phishsense-86ed4',
    storageBucket: 'phishsense-86ed4.firebasestorage.app',
    iosBundleId: 'com.example.phishsenseSms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb5p-ovphSdVojqVAaTfcnoYFDFWYrWws',
    appId: '1:605252089782:ios:94d0ad9a1367c7cdb43317',
    messagingSenderId: '605252089782',
    projectId: 'phishsense-86ed4',
    storageBucket: 'phishsense-86ed4.firebasestorage.app',
    iosBundleId: 'com.example.phishsenseSms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxVEbSH_RtyJte26KU6-6MSdA9okN3U8U',
    appId: '1:605252089782:web:f8bd1fb70401edc2b43317',
    messagingSenderId: '605252089782',
    projectId: 'phishsense-86ed4',
    authDomain: 'phishsense-86ed4.firebaseapp.com',
    storageBucket: 'phishsense-86ed4.firebasestorage.app',
    measurementId: 'G-47ENS7HQB7',
  );
}
